# Generated by Django 5.1.2 on 2024-11-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="biography",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
