# Generated by Django 5.1.2 on 2024-11-02 22:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_biography_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="biography",
            name="bio",
            field=tinymce.models.HTMLField(),
        ),
    ]
