# Generated by Django 5.1.2 on 2024-11-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_biography_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="biography",
            name="profilepicture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profilepictures/"
            ),
        ),
    ]
