# Generated by Django 5.1.2 on 2024-11-03 00:32

import tinymce.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Biography",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bio", tinymce.models.HTMLField()),
                (
                    "profilepicture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profilepictures/"
                    ),
                ),
            ],
        ),
    ]
