# Generated by Django 5.1.2 on 2024-11-03 18:42

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", tinymce.models.HTMLField()),
                (
                    "projectpicture",
                    models.ImageField(
                        blank=True, null=True, upload_to="projectpictures/"
                    ),
                ),
            ],
        ),
    ]
